POST http://localhost:3000/api/teachers
Content-Type: application/json

{
    "dni": "77777777X",
    "fullname": "POST AISLADO",
    "email": "aislado@correo.com",
    "active": 1,
    "status": "ALTA",
    "teaching_hours": 5,
    "hourly_rate": "30.00",
    "hire_date": "2026-02-03",
    "image_url": "https://picsum.photos/seed/postteacher/300/300
}
