### GET todos los profesores
GET http://localhost:3000/api/teachers

### GET profesor por id (usa uno que ya exista)
GET http://localhost:3000/api/teachers/1

### GET profesor por id (usa uno que no existe)
GET http://localhost:3000/api/teachers/50



### POST nuevo profesor
POST http://localhost:3000/api/teachers
Content-Type: application/json

{
  "dni": "99999999Z",
  "fullname": "Profesor Prueba",
  "email": "prueba@correo.com",
  "active": 1,
  "status": "ALTA",
  "teaching_hours": 10,
  "hourly_rate": "25.00",
  "hire_date": "2026-02-01",
  "image_url": null
}

### PUT profesor (id existente)
PUT http://localhost:3000/api/teachers/1
Content-Type: application/json

{
  "fullname": "Profesor Actualizado"
}

### DELETE profesor
DELETE http://localhost:3000/api/teachers/4
